Repository mcsp-blue-ocean/quest, pull requests merged in 2023-12, with the labels that each got.

#21 14 create a readmemd
  README.md
Labels: documentation

#73 72 uiux fix tech icons being fixed size in chrome
  client/src/Landing/Tech.jsx
  client/src/Landing/techData.js
Labels: bug

#109 Chatbot prototype
  client/src/App.jsx
  client/src/Chatbot.jsx
  client/src/assets/chatbot.svg
Labels: enhancement
